# https://github.com/actions/labeler#common-examples
# Adapted from https://github.com/rapidsai/dask-cuda/blob/main/.github/CODEOWNERS
# Labels culled from https://github.com/rapidsai/dask-cuda/labels

Python:
 - 'dask_cuda/**'

cpp:
 - 'cpp/**'

CMake:
 - '**/CMakeLists.txt'
 - '**/cmake/**'

ci:
  - 'ci/**'

conda:
  - 'conda/**'

